Core/urls.py
from django.urls import path
from .views import departments,detail

app_name='Core'

urlpatterns = [
    path('departments/',departments,name='departments'),
    path('detail/<int:id>',detail,name='detail'),
    # path('table_detail/<int:id>',table_detail,name='table_detail'),
   
]

User/urls.py
from django.urls import path
from .views import register, Logout, login

app_name='User'

urlpatterns = [
    path('register/', register, name = 'register'),
    path('logout/', Logout, name = 'logout'),
    path('login/', login, name = 'login'),
    

]

Week_Planning/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from Core.views import index





urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name = "index"),
    path('core/',include("Core.urls",namespace="core")),
    path('user/',include("User.urls",namespace="user")),
    
]

Core/models.py
from django.db import models
# from User.models import User



class Department(models.Model):
    name=models.CharField(max_length=50,unique=True)
    
    
    def __str__(self):
        return self.name
    
    
class TheTable(models.Model):
   name=models.CharField(max_length=50,null=True)
   worker=models.OneToOneField(to='User.User',null=True,blank=True,on_delete=models.SET_NULL,related_name='table')
   department=models.ForeignKey(Department,on_delete=models.CASCADE,blank=True,null=True)
   def __str__(self):
        return str(self.id)

User/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from Core.models import Department

STATUS_CHOICES=(
    (1,"on_side"),
    (2,"remote"),
    )

class User(AbstractUser):
    STATUS_CHOICES=(
        (1,"on_side"),
        (2,"remote"),
    )
    
    bio = models.TextField(max_length=500, blank=True)
    image = models.ImageField(upload_to = "user_avatars" ,blank = True, null = True)
    department=models.ForeignKey(Department,null=True,blank=True,on_delete=models.SET_NULL,related_name='workers')
    status=models.IntegerField(choices=STATUS_CHOICES,default=1)

User/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
User = get_user_model()






class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'User name',
        'class': 'form-control'
        }

    ))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'First name',
        'class': 'form-control'
        }

    ))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Last name',
        'class': 'form-control'
        }

    ))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Email',
        'class': 'form-control'
    
        }

    ))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password1',
        'class': 'form-control'
        }

    ))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password2',
        'class': 'form-control'
        }

     ))
    

       



class LoginForm(forms.Form):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class': 'form-control'
    
        }

    ))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter your password',
        'class': 'form-control'
        }

    ))
    

Core/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .models import Department,TheTable
from User.models import User
from django.contrib import messages

import pdb

def index(request):
    return render(request,'index.html')


    
def detail(request,id):
    onsides=[]
    remotes=[]
    tables=TheTable.objects.filter(department=id)
    employees=User.objects.filter(department_id=id)
    
    if request.method=="POST":
        # pdb.set_trace()
        worker_id=request.user.id
        table_id=request.POST['id']
        table=TheTable.objects.get(id=table_id)
        worker=User.objects.get(id=worker_id)

        if worker.status == 1:
            
            # if TheTable.objects.filter(worker__id=worker_id):
            #     messages.error(request,"User table secib")
            #     return redirect('/')
    
            if not table.worker:
                table.worker=User.objects.get(id=worker_id)
                table.save()      
                
            elif table.worker and TheTable.objects.filter(worker__id=worker_id):
                table.worker=None
                table.save()
            
        else:
            messages.error(request,"Siz remote işləyəcəksiniz...")
            return redirect('/')            

            
    workers=TheTable.objects.all()
    for employee in employees:
        if employee.status == 1:
            onsides.append(employee)
          
        elif employee.status == 2:
            remotes.append(employee)
            
           
    context={
            'onsides': onsides,
            'remotes': remotes,
            'tables' : tables,
            'select_table': workers,
        }
    return render(request,'employees.html',context)



def departments(request):
    departments=Department.objects.all()
    return render(request,"departments.html",{"departments":departments})

User/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login, authenticate,logout
from django.contrib import messages
from .forms import RegisterForm , LoginForm
from django.contrib.auth.decorators import login_required



def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()

            messages.success(request, f'Hesabınız uğurla yaradıldı')    
            return redirect('user:login')
    else:
        form = RegisterForm()

    context = {'form': form}
    return render(request, 'register.html', context)

def login(request):
    context= {}
    context['form'] = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                auth_login(request, user)
                print('User is here!!!')
                return redirect('index')

            print('===================')

    return render(request, 'login.html', context)


def Logout(request):
    logout(request)
    messages.success(request,'Uğurla logout oldunuz...')
    return redirect('index')
    

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"  href:"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    {% comment %} <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> {% endcomment %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> 
    {% comment %} <link  rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"> {% endcomment %}
    <title>Week Planning</title>
</head>
<body>
{% include "includes/navbar.html" %}
{% block content %}  

{% endblock %} 
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script> 
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script> 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>  
</body> 
</html>

templates/departments.html
{%extends 'base.html'%}
{% block content %}
<br>
<br>
<br>
<h3 style="margin-left:500px;">Departamentlər</h3>

<hr>
<br>
<div style="margin-left:440px;">
{% for department in departments %}
<a href="{% url 'Core:detail' department.id %}" class='btn btn-danger' >{{department.name}}</a>
{% endfor %}

</div>

{% endblock %}

templates/employees.html
{%extends 'base.html'%}
{% load static %}
{% block content %}
<br><br><br>

<h3 style='margin-left:400px; color:green;'>İŞÇİLƏRİN SİYAHISI</h3>
<br><br>
<div class='row'>
    <div class='col-6'>
      <table border='1' width="100%" cellpadding="5" cellspacing="0">
        <tr>
          <th  >Ofisdə işləyəcək işçilər</th>
        </tr>
          <tr>
            <td >
              <table>
            {% for employee in onsides %}
                  <tr><td>{{ employee.username}}</td></tr>
            {% endfor %}
              </table>
            </td>
          </tr>
      </table>
    </div>
<br><br>

    <div class='col-6'>
      <table border='1' width="100%"  cellpadding="5" cellspacing="0">
        <tr >
          <th>Remote işləyəcək işçilər</th>
        </tr>
          <tr>
            <td >
              <table>
            {% for employee in remotes %}
                  <tr><td>{{employee.username }}</td></tr>
            {% endfor %}
              </table>
            </td>
          </tr>
      </table>
  </div>
</div>

<hr>
<br><br><br>
<div  style="display:flex; width:500px">
 
  {% for table in tables %}

    <form action="" method="POST">
      {% csrf_token %}
      <input style="margin-left:300px;" name="id" type="hidden" value="{{table.id}}">
      {% if table.worker %}
      <button style="margin-left:50px;height:50px;width:100px;background-color:red;" type="submit">{{table.name}}</button>
      {% else %}
      <button style="margin-left:50px;height: 50px;width:50px;background-color:green" type="submit">{{table.name}}</button>
      {%  endif %}
      
    </form>
    <hr>
  {% endfor %}

</div>
<br><br>
<div  >
<table  border="1" width="400px" style="margin-left:300px">
  <tr>
    <th>Işçinin adı və əyləşəcəyi masa</th>
    

  </tr>
{% for i in select_table %}
  {% if i.worker %}
  <tr>
    <td>{{i.worker}} masa {{i.name}}-də əyləşəcək</td>
  </tr>
 {% endif %}
  {% endfor %}
</table>
</div>
  {% endblock %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        {% if request.user.is_authenticated %}  
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Əsas səhifə<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:departments' %}">Departamentlər</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="{% url 'user:logout'%}">Çıxış</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link disabled" href="{% url 'user:login' %}">Giriş</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link disabled" href="{% url 'user:register' %}">Qeydiyyatdan keç </a>
        </li>
      </ul>
     
    </div>
  </nav>

templates/index.html
{% extends 'base.html'%}
{% block content %}
<br><br>
<main role="main" class="container"  >
  {% if messages %}
    {% for message in messages %}
      {% if message.tags == "error"%}
      <div class="alert alert-danger">
        {{ message }}
      </div>
      {% else %}
      <div class="alert alert-success">
        {{ message }}
      </div>
      {% endif %}
    {% endfor %}
  {% endif %}
 {% if request.user.is_authenticated %}

<div class="jumbotron text-center">
    <h3>"Week Planning" səhifəsinə Xoş gəldiniz,{{request.user.username}}!</h3>
    <p>Çalışma cədvəli ilə tanış olmaq üçün,<a href="{% url 'core:departments' %}">
        bura keçid edə bilərsiniz.</a></p>
</div>

<p>
   
    {% else %}
    <div class="jumbotron text-center">
        <h3>"Week Planning" səhifəsinə Xoş gəldiniz!!!</h3>
        <p>Bu səhifədə hər departamentin əməkdaşı öz çalışma cədvəlini aydın şəkildə görə bilər.</p>
    </div>
    
    <p>
    {% endif %}

</p>

{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>Login səhifəsi</title>
{% endblock %}
{% block content %}
<br><br><br>
<div class="row">
<div class="col-md-6 offset-md-3">
<h3>login</h3>

<form action="" method="POST">
    {% csrf_token %}
    {% for field in form %}
    <p >{{ field.label }}: <br> {{ field }}</p> 
    {% endfor %}

    <button type="submit" class="btn btn-danger">Login</button>
</form>

<p>Hesabınız yoxdur? <a href="{% url 'user:register' %}">
    Burada qeydiyyatdan keçin</a></p>
</div>
</div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% comment %} {% load crispy_forms_tags %} {% endcomment %}

{% block content %}
<br><br><br>
<div class="row">
<div class="col-md-6 offset-md-3">
    <h3>Qeydiyyat formu</h3>  
    <br>  
<form action="" method="POST">
    {% csrf_token %}

    {% for field in form %}
            <p >{{ field }}</p> 

            {% for error in field.errors %}
                <small style="color: red">{{ error }}</small>
            {% endfor %}
    {% endfor %}
    <button type="submit"class = "btn btn-danger">Qeydiyyatdan keçin</button>
</form>
</div>
</div>

{% endblock %}